# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import call_processing_pb2 as call__processing__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in call_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscriptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/callprocessing.v1.TranscriptionService/Transcribe',
                request_serializer=call__processing__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=call__processing__pb2.TranscribeResponse.FromString,
                _registered_method=True)


class TranscriptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=call__processing__pb2.TranscribeRequest.FromString,
                    response_serializer=call__processing__pb2.TranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callprocessing.v1.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callprocessing.v1.TranscriptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callprocessing.v1.TranscriptionService/Transcribe',
            call__processing__pb2.TranscribeRequest.SerializeToString,
            call__processing__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RoutingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Route = channel.unary_unary(
                '/callprocessing.v1.RoutingService/Route',
                request_serializer=call__processing__pb2.RouteRequest.SerializeToString,
                response_deserializer=call__processing__pb2.RouteResponse.FromString,
                _registered_method=True)


class RoutingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Route(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=call__processing__pb2.RouteRequest.FromString,
                    response_serializer=call__processing__pb2.RouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callprocessing.v1.RoutingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callprocessing.v1.RoutingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoutingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callprocessing.v1.RoutingService/Route',
            call__processing__pb2.RouteRequest.SerializeToString,
            call__processing__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EntityExtractionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractEntities = channel.unary_unary(
                '/callprocessing.v1.EntityExtractionService/ExtractEntities',
                request_serializer=call__processing__pb2.ExtractEntitiesRequest.SerializeToString,
                response_deserializer=call__processing__pb2.ExtractEntitiesResponse.FromString,
                _registered_method=True)


class EntityExtractionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntityExtractionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEntities,
                    request_deserializer=call__processing__pb2.ExtractEntitiesRequest.FromString,
                    response_serializer=call__processing__pb2.ExtractEntitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callprocessing.v1.EntityExtractionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callprocessing.v1.EntityExtractionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EntityExtractionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callprocessing.v1.EntityExtractionService/ExtractEntities',
            call__processing__pb2.ExtractEntitiesRequest.SerializeToString,
            call__processing__pb2.ExtractEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TicketServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTicket = channel.unary_unary(
                '/callprocessing.v1.TicketService/CreateTicket',
                request_serializer=call__processing__pb2.CreateTicketRequest.SerializeToString,
                response_deserializer=call__processing__pb2.CreateTicketResponse.FromString,
                _registered_method=True)


class TicketServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTicket,
                    request_deserializer=call__processing__pb2.CreateTicketRequest.FromString,
                    response_serializer=call__processing__pb2.CreateTicketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callprocessing.v1.TicketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callprocessing.v1.TicketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicketService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callprocessing.v1.TicketService/CreateTicket',
            call__processing__pb2.CreateTicketRequest.SerializeToString,
            call__processing__pb2.CreateTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCall = channel.unary_unary(
                '/callprocessing.v1.OrchestratorService/ProcessCall',
                request_serializer=call__processing__pb2.ProcessCallRequest.SerializeToString,
                response_deserializer=call__processing__pb2.ProcessCallResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCall': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCall,
                    request_deserializer=call__processing__pb2.ProcessCallRequest.FromString,
                    response_serializer=call__processing__pb2.ProcessCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callprocessing.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callprocessing.v1.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callprocessing.v1.OrchestratorService/ProcessCall',
            call__processing__pb2.ProcessCallRequest.SerializeToString,
            call__processing__pb2.ProcessCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NotificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNotification = channel.unary_unary(
                '/callprocessing.v1.NotificationService/SendNotification',
                request_serializer=call__processing__pb2.SendNotificationRequest.SerializeToString,
                response_deserializer=call__processing__pb2.SendNotificationResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=call__processing__pb2.SendNotificationRequest.FromString,
                    response_serializer=call__processing__pb2.SendNotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callprocessing.v1.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callprocessing.v1.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callprocessing.v1.NotificationService/SendNotification',
            call__processing__pb2.SendNotificationRequest.SerializeToString,
            call__processing__pb2.SendNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
